#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

OPPOSITE=right

if [[ "$1" == "right" ]]; then
    OPPOSITE=left
fi

if [[ "$1" == "up" ]]; then
    OPPOSITE=down
fi

if [[ "$1" == "down" ]]; then
    OPPOSITE=up
fi

# swaymsg border csd || swaymsg border normal

CURRENT_WORKSPACE=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused == true)' | jq -r .id)
swaymsg focus "$1"
NEW_WORKSPACE=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused == true)' | jq -r .id)

if [[ "$CURRENT_WORKSPACE" -ne "$NEW_WORKSPACE" ]]; then
    swaymsg focus "$OPPOSITE"
fi

# swaymsg border csd || swaymsg border pixel 2
# swaymsg border csd || swaymsg border normal
