#!/bin/sh

# FROM https://gist.githubusercontent.com/ckafi/0a5b79105c8301466cc324a08200aad7/raw/5117f2cd21b7b9bc74298cb205370b36fe4cf825/track_prev_focus

prev_focus=$(swaymsg -r -t get_seats | jq '.[0].focus')

swaymsg -m -t subscribe '["window"]' | \
  jq --unbuffered 'select(.change == "focus").container.id' | \
  while read new_focus; do
    swaymsg "[con_id=${prev_focus}] mark --add _prev" &>/dev/null
    prev_focus=$new_focus
  done
