#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Generate ~/.backup by `pass ls Backup/ | sed '1d' | sed 's/.* //' | parallel -j 1 pass show Backup/{} '|' awk -v PASSWORD_NAME=RESTIC_PASSWORD -v PRE=BACKUPARG_ -f serialize_gnu_pass.awk BACKUPARG_RESTIC_REPOSITORY_NAME={=s/.*://=} > ~/.backup`

SELECTED=""
if [ "$#" -eq 1 ]; then
    SELECTED="$1"
fi

ENVIRONMENT_FILE=$HOME/.backup
BACKUP_NAMES=$(cat "$ENVIRONMENT_FILE" | jq -r .BACKUPARG_RESTIC_REPOSITORY_NAME)
for BACKUP_NAME in $BACKUP_NAMES; do

    if [ "$SELECTED" != "" ] && [ "$SELECTED" != "$BACKUP_NAME" ]; then
        continue
    fi


    LINE="$(cat "$ENVIRONMENT_FILE" | jq "select(.BACKUPARG_RESTIC_REPOSITORY_NAME == \"$BACKUP_NAME\")")"
    echo ">> $BACKUP_NAME = $LINE"
    . ndjson-env -a "$LINE"

    # BACKUPARG_SUBVOL=""                 # FROM ndjson
    # BACKUPARG_INTERNAL_DIRECTORY=""     # FROM ndjson
    # BACKUPARG_RESTIC_REPOSITORY_NAME="" # FROM ndjson
    # BACKUPARG_LOGICAL_VOLUME=""         # FROM ndjson

    export BACKUPARG_VOLUME_GROUP="store"
    export BACKUPARG_SNAP_PRE="baksnap"
    export BACKUPARG_DEVICE="/dev/$BACKUPARG_VOLUME_GROUP/$BACKUPARG_LOGICAL_VOLUME"
    export BACKUPARG_DEVICE_MOUNTPOINT="/mnt/baksnap"
    export BACKUPARG_RESTIC_REPOSITORY_ROOT="sftp://badmin@b.lang.speechmarks.com://mnt/restic_sftp"
    export BACKUPARG_METHOD=sftp

    backup_worker
done

