#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

function positions() {
    local OUT
    OUT=$(xdotool getwindowgeometry "$1" | paste -d " " - - - )
    RE="Position: ([0-9]+),([0-9]+).*Geometry: ([0-9]+)x([0-9]+)"
    if [[ "$OUT" =~ $RE ]]; then
        echo "$1 L:${BASH_REMATCH[1]} T:${BASH_REMATCH[2]} W:${BASH_REMATCH[3]} H:${BASH_REMATCH[4]} R:$((${BASH_REMATCH[1]}+${BASH_REMATCH[3]})) B:$((${BASH_REMATCH[2]}+${BASH_REMATCH[4]})) M:$((${BASH_REMATCH[1]}+${BASH_REMATCH[3]}/2)) N:$((${BASH_REMATCH[2]}+${BASH_REMATCH[4]}/2))"
        return
    else
        exit 1
    fi
}
export -f positions

function left_area() {
	RE="T:([0-9]+).*B:([0-9]+).*M:([0-9]+)"
    if [[ "$1" =~ $RE ]]; then
    	echo "L:0 T:${BASH_REMATCH[1]} R:${BASH_REMATCH[3]} B:${BASH_REMATCH[2]}"
    	return
    fi
    exit 1
}

function right_area() {
	RE="T:([0-9]+).*B:([0-9]+).*M:([0-9]+)"
    if [[ "$1" =~ $RE ]]; then
    	echo "L:${BASH_REMATCH[3]} T:${BASH_REMATCH[1]} R:$2 B:${BASH_REMATCH[2]}"
    	return
    fi
    exit 1
}

function top_area() {
	RE="L:([0-9]+).*R:([0-9]+).*N:([0-9]+)"
    if [[ "$1" =~ $RE ]]; then
    	echo "L:${BASH_REMATCH[1]} T:0 R:${BASH_REMATCH[2]} B:${BASH_REMATCH[3]}"
    	return
    fi
    exit 1
}

function bottom_area() {
	RE="L:([0-9]+).*R:([0-9]+).*N:([0-9]+)"
    if [[ "$1" =~ $RE ]]; then
    	echo "L:${BASH_REMATCH[1]} T:${BASH_REMATCH[3]} R:${BASH_REMATCH[2]} B:$3"
    	return
    fi
    exit 1
}

DESKTOP=$(xdotool get_desktop)
WINS=$(wmctrl -l | grep "[^ ]\+ \+$DESKTOP " | sed 's/ .*//' | parallel --halt now,fail=1 positions {})
ACTIVE_WIN=$(printf '0x%08x\n' "$(xdotool getactivewindow)")
DESKTOP_WIDTH=9999
DESKTOP_HEIGHT=9999
DESKTOP_GEOM_RE="^([0-9]+) ([0-9]+)"
if [[ "$(xdotool getdisplaygeometry)" =~ $DESKTOP_GEOM_RE ]]; then
    DESKTOP_WIDTH="${BASH_REMATCH[1]}"
    DESKTOP_HEIGHT="${BASH_REMATCH[2]}"
else
    echo "Could not find desktop geometry"
    exit 1
fi

# echo "DESKTOP: $DESKTOP @ ${DESKTOP_WIDTH}x${DESKTOP_HEIGHT}"
# echo "WINS: "
# echo ""
# echo "$WINS"
# echo "ACTIVE_WIN: $ACTIVE_WIN"
# echo "LEFT: $(left_area "$(echo "$WINS" | grep "$ACTIVE_WIN")" "$DESKTOP_WIDTH" "$DESKTOP_HEIGHT")"
# echo "RIGHT: $(right_area "$(echo "$WINS" | grep "$ACTIVE_WIN")" "$DESKTOP_WIDTH" "$DESKTOP_HEIGHT")"
# echo "TOP: $(top_area "$(echo "$WINS" | grep "$ACTIVE_WIN")" "$DESKTOP_WIDTH" "$DESKTOP_HEIGHT")"
# echo "BOTTOM: $(bottom_area "$(echo "$WINS" | grep "$ACTIVE_WIN")" "$DESKTOP_WIDTH" "$DESKTOP_HEIGHT")"


#!/bin/bash
set -euo pipefail

show_help() {
    echo "NAME:"
    echo "  $0 - Switches windows based on position"
    echo ""
    echo "USAGE:"
    echo "  $0 DIRECTION"
    echo ""
    echo "ARGUMENTS:"
    echo "  DIRECTION     This must be one of up, down, left or right"
    echo ""
}

if [ $# -gt 0 ] && [ "$1" == "help" ]; then
    show_help
    exit 0
fi


AREA="L:0 T:0 R:0 B:0"
if [ "$1" == "up" ]; then
    AREA="$(top_area "$(echo "$WINS" | grep "$ACTIVE_WIN")" "$DESKTOP_WIDTH" "$DESKTOP_HEIGHT")"
fi

if [ "$1" == "down" ]; then
    AREA="$(bottom_area "$(echo "$WINS" | grep "$ACTIVE_WIN")" "$DESKTOP_WIDTH" "$DESKTOP_HEIGHT")"
fi

if [ "$1" == "left" ]; then
    AREA="$(left_area "$(echo "$WINS" | grep "$ACTIVE_WIN")" "$DESKTOP_WIDTH" "$DESKTOP_HEIGHT")"
fi

if [ "$1" == "right" ]; then
    AREA="$(right_area "$(echo "$WINS" | grep "$ACTIVE_WIN")" "$DESKTOP_WIDTH" "$DESKTOP_HEIGHT")"
fi

function within() {
	RE="M:([0-9]+).*N:([0-9]+)"
    if [[ "$5" =~ $RE ]]; then
        M="${BASH_REMATCH[1]}"
        N="${BASH_REMATCH[2]}"
        if [ "$M" -gt "$1" ] && [ "$M" -lt "$3" ] && [ "$N" -gt "$2" ] && [ "$N" -lt "$4" ]; then
            return 0
        fi
    fi
    return 1
}

function get_horiz() {
	RE="M:([0-9]+)"
    if [[ "$1" =~ $RE ]]; then
        echo "${BASH_REMATCH[1]}"
        exit 0
    fi
    exit 1
}

function get_vert() {
	RE="N:([0-9]+)"
    if [[ "$1" =~ $RE ]]; then
        echo "${BASH_REMATCH[1]}"
        exit 0
    fi
    exit 1
}

function get_winid() {
	RE="^([^ ]+)"
    if [[ "$1" =~ $RE ]]; then
        echo "${BASH_REMATCH[1]}"
        exit 0
    fi
    exit 1
}

RE="L:([0-9]+).*T:([0-9]+).*R:([0-9]+).*B:([0-9]+)"
echo "AREA: $AREA"
if [[ "$AREA" =~ $RE ]]; then
    L="${BASH_REMATCH[1]}"
    T="${BASH_REMATCH[2]}"
    R="${BASH_REMATCH[3]}"
    B="${BASH_REMATCH[4]}"
else
    exit 1
fi
for W in $WINS; do
    set +e
    if within "$L" "$T" "$R" "$B" "$W"; then
        set -e
        echo "IN $W"
        if [ "$1" == "right" ]; then
            R="$(get_horiz "$W")"
        fi
        if [ "$1" == "left" ]; then
            L="$(get_horiz "$W")"
        fi
        if [ "$1" == "up" ]; then
            T="$(get_vert "$W")"
        fi
        if [ "$1" == "down" ]; then
            B="$(get_vert "$W")"
        fi
        echo "FOCUS: $(get_winid "$W")"
        xdotool windowactivate "$(get_winid "$W")"
    else
        echo "OUT $W"
    fi
    echo "> $L $T $R $B"
    set -e
done
