#!/bin/bash

TMUX_SESSION=$1
if [ "$#" -lt 1 ]; then
    TMUX_SESSION="default"
fi


FOUND_SESSION="$(ka -N | grep FOUND | awk '{ print $2 }')"
if [ "${#FOUND_SESSION}" -eq 0 ]; then
    echo "No Kakoune session found"
    exit 1
fi

if xmux list_session "$FOUND_SESSION" | awk -F ':' '{ print $1 }' | grep -F "$TMUX_SESSION"; then
    echo "ALREADY EXISTS"
    tmux -L 2791745 attach -t default
else
    xmux new "$FOUND_SESSION" "$TMUX_SESSION"
fi
