#!/bin/bash


show_help() {
    echo "$1 <TMUX_SESSION> [TMUX_WINDOW]"
    echo ""
    echo "-h = Display this help"
    echo ""
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            show_help
            exit 0
            ;;
    esac
done
shift $(( OPTIND - 1 ))


TMUX_SESSION="$(get_directory_identity)"
if [ "$#" -gt 0 ]; then
    TMUX_SESSION="$1"
fi
CONSOLE="default"
if [ "$#" -gt 1 ]; then
    CONSOLE="$2"
fi

if xmux ensure "$TMUX_SESSION" "$CONSOLE"; then
    echo "ALREADY EXISTS"
    tmux -L "$TMUX_SESSION" attach -t "$CONSOLE"
else
    xmux new "$TMUX_SESSION" "$CONSOLE"
fi



