#!/bin/bash


IN_SQL=""
while read line
do
    IN_SQL="${IN_SQL} $line"
done < "${1:-/dev/stdin}"


if [ -z "$IN_SQL" ]; then
    IN_SQL=$1
fi

set -euo pipefail
IFS=$'\n\t'

psql -c "COPY (${IN_SQL}) TO STDOUT WITH CSV HEADER NULL AS '' DELIMITER AS E'\t'"

exit $?
