#!/bin/bash


IN_SQL=""
while read line
do
    IN_SQL="${IN_SQL} $line"
done < "${1:-/dev/stdin}"


if [ -z "$IN_SQL" ]; then
    IN_SQL=$1
fi

set -euo pipefail
IFS=$'\n\t'


UUID=$(uuidgen | sed 's/\-//g')

echo  "select row_to_json(x$UUID) from ( $IN_SQL ) x$UUID" | psql -t | grep -v '^$'  | sed 's/^\s\+//'

exit $?
