#!/bin/bash


IN_SQL=""
while read line
do
    IN_SQL="${IN_SQL} $line"
done < "/dev/stdin"

set -euo pipefail
IFS=$'\n\t'

echo "$IN_SQL" |  psql-out -f csv | sed '1 sI[^,]*,I@ I' | termgraph "$@"

exit $?
