#!/bin/bash

if [ ! -f /tmp/.slide-show ]; then
    echo "BUILDING"
    find $@ | grep '\(\.jpg\|\.jpeg\|\.gif\|\.png\)$' > /tmp/.slide-show
    exit 0
fi
FILTER='.'
if [ "$#" -gt 1 ]; then
    FILTER="$2"
fi
COUNT=$(cat /tmp/.slide-show | grep "$FILTER" | wc -l | sed 's/ .*//')
echo $COUNT

I=0
while [ $I -lt $1 ];
do
    ((I++))
    NUM=$((1+($RANDOM%$COUNT)))
    IMG=$(cat /tmp/.slide-show | grep -v '+' | grep "$FILTER" | sed "${NUM}q;d")
    feh -F -Z "$IMG" &
    sleep 5
    echo $IMG
    killall feh
done
