#!/bin/bash

find | grep '\(\.jpg\|\.jpeg\|\.gif\|\.png\)$' > /tmp/.slide-show
COUNT=$(cat .slide-show | wc -l | sed 's/ .*//')
echo $COUNT

I=0
while [ $I -lt $1 ];
do
    ((I++))
    NUM=$((1+($RANDOM%$COUNT)))
    IMG=$(sed "${NUM}q;d" .slide-show)
    feh -F -Z "$IMG" &
    sleep 5
    echo $IMG
    killall feh
done
rm /tmp/.slide-show
