#!/bin/bash

shopt -s nullglob

DESIRED_PROFILE=$1
CURRENT_PATH=$PWD
POSSIBLE_PROFILE_PREFERENCES=($GOOGLE_CHROME_USER_SETTINGS_DIRECTORY/*/Preferences)

if [ "$GOOGLE_CHROME_USER_SETTINGS_DIRECTORY" = "" ]; then
    echo "Error: You must set the environmental variable $GOOGLE_CHROME_USER_SETTINGS_DIRECTORY"
    exit 2
fi

for POSSIBLE_PREFERENCE in "${POSSIBLE_PROFILE_PREFERENCES[@]}"; do
    NAME=$(cat "$POSSIBLE_PREFERENCE" | jq -r .profile.name)
    if [ "$NAME" = "$DESIRED_PROFILE" ]; then
        GOOGLE_PROFILE_DIRECTORY=$(echo "$POSSIBLE_PREFERENCE" | sed 'sI.*/\(.*\)\/.*I\1I')
            if [ "$#" -gt "1" ]; then
                google-chrome --profile-directory="$GOOGLE_PROFILE_DIRECTORY" "$2"
            else
                google-chrome --profile-directory="$GOOGLE_PROFILE_DIRECTORY"
            fi
        exit 0
    fi
done
echo "Error: Could not find Google Chrome Profile '$DESIRED_PROFILE'"
exit 1
