#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

MAIN_OUTPUT=$(swaymsg -t get_outputs | cat | jq '.[] | select(.focused == true)' | jq -r .name)
OTHER_OUTPUT=$(swaymsg -t get_outputs | cat | jq '.[] | select(.focused == false)' | jq -r .name)
CURRENT_WORKSPACE=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused == true)' | jq -r .name)

for ITEM in $(swaymsg -t get_workspaces | jq -r '.[] | .name'); do
	swaymsg "workspace ${ITEM}"
	swaymsg "move workspace to output ${MAIN_OUTPUT}"
done

swaymsg "workspace 0"
swaymsg "move workspace to output ${OTHER_OUTPUT}"
swaymsg "workspace ${CURRENT_WORKSPACE}"
