#!/bin/bash

CPU_COUNT=$(cat /proc/cpuinfo | awk '/^processor/{print $3}' | wc -l)

OUT="100"
for l in $(uptime | sed 's/.*\://' | sed 's/,//g'); do
    printf -v jlh "%0.0f" $(echo "scale=2; ($l / $CPU_COUNT) * 100" | bc -l)
    OUT="$OUT $jlh"
done
GRAPH=$(echo $OUT | spark)
echo "${GRAPH:1} $(free -w | awk '/Mem:/ { total=$2 } /Mem:/ { used=$8 } END { print (used / total) * 100}' | sed 's/\..*//')%/$(free -w | awk '/Swap:/ { total=$2 } /Swap:/ { used=$3 } END { print (used / total) * 100}' | sed 's/[\.].*//')%"

