#!/bin/bash

fzf --help

if [[ $? -ne 0 ]]; then
    echo "FZF is not installed"
    sleep 5
    exit 1
fi

BACK_TO=$(tmux list-windows | grep '\- (' | sed 's/:.*//')
if [ $? -ne 0 ]; then
    exit 1
fi

GO_TO=$(tmux list-sessions | sed 's/\:.*//' | sed 's/^\(.\)\:/0\1:/'| fzf --reverse -1)

if [ $? -ne 0 ]; then
    tmux select-window -t $BACK_TO
    exit 0
fi
tmux switch -t $(echo $GO_TO | sed 's/:.*//')

