#!/bin/bash

# fzf --help

if [[ $? -ne 0 ]]; then
    echo "FZF is not installed"
    sleep 5
    exit 1
fi

function goto {
    tmux select-window -t $(echo "$1" | sed 's/:.*//')
    return $?
}

HIDE_SWICTHER=$(tmux list-windows | grep '\* (' | sed 's/:.*/:/')
BACK_TO=$(tmux list-windows | grep '\- (' | sed 's/:.*//')
if [ $? -ne 0 ]; then
    exit 1
fi

MATCHES="$(tmux list-windows | grep -v "^$HIDE_SWICTHER" | sed 's/(.*//' | sed 's/^\(.\)\:/0\1:/' | grep -F "$1")"
if [ "$(printf '%s' "$MATCHES" | awk '{ print $0 }' | wc -l)" -eq 1 ]; then
    goto "$MATCHES"
else
    if [[ $1 == "_" ]]; then
        goto "$(tmux list-windows | grep -v "^$HIDE_SWICTHER" | sed 's/(.*//' | sed 's/^\(.\)\:/0\1:/'| fzf --reverse -e -1)"
    else
        goto "$(tmux list-windows | grep -v "^$HIDE_SWICTHER" | sed 's/(.*//' | sed 's/^\(.\)\:/0\1:/'| fzf --reverse -e -1 -q $1)"
    fi
fi

