#!/bin/bash

HIDE_SWICTHER=$(tmux list-windows | grep '\* (' | sed 's/:.*/:/')
BACK_TO=$(tmux list-windows | grep '\- (' | sed 's/:.*//')
if [ $? -ne 0 ]; then
    exit 1
fi
GO_TO=$(tmux list-windows | grep -v "^$HIDE_SWICTHER" | sed 's/(.*//' | sed 's/^\(.\)\:/0\1:/'| fzf --reverse -q $1)
if [ $? -ne 0 ]; then
    tmux select-window -t $BACK_TO
    exit 0
fi
tmux select-window -t $(echo $GO_TO | sed 's/:.*//')
