#!/bin/bash

WIDS=$(tmux list-windows | sed 's/:.*//' | grep "^$1")

if [ $(echo $WIDS | wc -w) -eq 0 ]; then
    WIDS=$(tmux list-windows | sed 's/:.*//' | grep "$1")
fi

if [ $(echo $WIDS | wc -w) -eq 1 ]; then
    tmux select-window -t $WIDS
    exit 0
fi

read -t 10 -p "Switch to window: $1" -s -n 1 WIN

tmux select-window -t $(echo "$1$WIN" | sed 's/^0//')
