#!/bin/bash

fzf --help

if [[ $? -ne 0 ]]; then
    echo "FZF is not installed"
    sleep 5
    exit 1
fi

HIDE_SWICTHER=$(tmux list-windows | grep '\* (' | sed 's/:.*/:/')
BACK_TO=$(tmux list-windows | grep '\- (' | sed 's/:.*//')
if [ $? -ne 0 ]; then
    exit 1
fi

# tmux list-windows | sed 's/(.*//' | sed 's/^\(.\)\:/0\1:/' |fzf  --tiebreak=begin --nth=1 --delimiter=':'

GO_TO=""
if [[ $1 == "_" ]]; then
    GO_TO=$(tmux list-windows | grep -v "^$HIDE_SWICTHER" | sed 's/(.*//' | sed 's/^\(.\)\:/0\1:/'| fzf --reverse -e -1)
else
    GO_TO=$(tmux list-windows | grep -v "^$HIDE_SWICTHER" | sed 's/(.*//' | sed 's/^\(.\)\:/0\1:/'| fzf --reverse -e -1 -q $1)
fi

if [ $? -ne 0 ]; then
    tmux select-window -t $BACK_TO
    exit 0
fi
tmux select-window -t $(echo $GO_TO | sed 's/:.*//')
